// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_bshorne.Models;

namespace Mission06_bshorne.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    [Migration("20230222041523_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_bshorne.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.HasIndex("CategoryID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            CategoryID = 1,
                            Director = "Gavin O'Connor",
                            Edited = true,
                            Notes = "Was an amazing movie",
                            Rating = "R",
                            Title = "The Accountant",
                            Year = 2016
                        },
                        new
                        {
                            ApplicationId = 2,
                            CategoryID = 1,
                            Director = "Christopher Nolan",
                            Edited = false,
                            Notes = "Was an amazing movie",
                            Rating = "PG-13",
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            ApplicationId = 3,
                            CategoryID = 1,
                            Director = "Tim Miller",
                            Edited = true,
                            Notes = "Was an amazing movie",
                            Rating = "R",
                            Title = "Deadpool",
                            Year = 2016
                        });
                });

            modelBuilder.Entity("Mission06_bshorne.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Adventure"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Musical"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Science Fiction"
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "Thriller"
                        });
                });

            modelBuilder.Entity("Mission06_bshorne.Models.ApplicationResponse", b =>
                {
                    b.HasOne("Mission06_bshorne.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
